# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
  - package-ecosystem: "cargo"
    directory: "/sqlx4k/rust_lib"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
  - package-ecosystem: "cargo"
    directory: "/sqlx4k-mysql/rust_lib"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
  - package-ecosystem: "cargo"
    directory: "/sqlx4k-postgres/rust_lib"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
  - package-ecosystem: "cargo"
    directory: "/sqlx4k-sqlite/rust_lib"
    schedule:
      interval: "weekly"
    assignees:
      - "smyrgeorge"
