server:
  port: 8082

spring:
  main:
    banner-mode: "off"
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/test?currentSchema=public
    username: postgres
    password: postgres
    pool:
      max-size: 40

logging:
  pattern:
    console: "%4relative %green(%d) %X{identity} [%thread] %highlight(${LOG_LEVEL_PATTERN:- %p}) %cyan(%logger{35}) - %msg%n"
  level:
    root: INFO