package io.github.smyrgeorge.sqlx4k.examples.sqlite

import io.github.smyrgeorge.sqlx4k.Connection
import io.github.smyrgeorge.sqlx4k.impl.coroutines.TransactionContext
import io.github.smyrgeorge.sqlx4k.sqlite.cipher.ISQLiteCipher
import kotlinx.coroutines.delay
import kotlin.time.Duration.Companion.milliseconds

/**
 * The same example scenarios as [Examples], but against the encrypted SQLite (SQLCipher) driver
 * ([ISQLiteCipher]). The driver-agnostic steps (which only need a `QueryExecutor`) are reused
 * directly from [Examples]; only the `ISQLiteCipher`-typed steps are re-implemented here.
 */
object CipherExamples {
    suspend fun runAll(db: ISQLiteCipher, repo: Sqlx4kRepository) {
        delay(2000.milliseconds)
        migrate(db)
        delay(1000.milliseconds)
        Examples.exampleBasics(db)
        delay(1000.milliseconds)
        Examples.examplePreparedStatements(db)
        delay(1000.milliseconds)
        exampleConnectionManagement(db)
        delay(1000.milliseconds)
        exampleTransactions(db, repo)
        delay(1000.milliseconds)
        exampleTransactionContext(db)
        delay(1000.milliseconds)
        Examples.exampleCrudRepository(db, repo)
        delay(1000.milliseconds)
        Examples.exampleAutoGeneratedRepository(db, repo)
        delay(1000.milliseconds)
        Examples.exampleBatchOperations(db, repo)
    }

    suspend fun migrate(db: ISQLiteCipher, path: String = "./db/migrations") {
        println("\n=== Migrate (SQLCipher) ===")
        val res = db.migrate(
            path = path,
            afterStatementExecution = { s, d -> println("Migration of statement: $s, took $d") },
            afterFileMigration = { m, d -> println("Migration of file: $m, took $d") }
        ).getOrThrow()
        println("Migration completed. $res")
    }

    suspend fun exampleConnectionManagement(db: ISQLiteCipher) {
        println("\n=== Connection management (SQLCipher) ===")
        println("Pool size: ${db.poolSize()} (idle: ${db.poolIdleSize()})")
        val cn: Connection = db.acquire().getOrThrow()
        try {
            println("Acquired connection. Pool size: ${db.poolSize()} (idle: ${db.poolIdleSize()})")
            // Use the dedicated connection
            cn.execute("delete from sqlx4k;").getOrThrow()
            cn.execute("insert into sqlx4k (id, test) values (10, 'from-conn');").getOrThrow()
            val rows = cn.fetchAll("select * from sqlx4k;", Sqlx4kRowMapper).getOrThrow()
            println("Rows via connection: $rows")
        } finally {
            cn.close().getOrThrow()
            delay(200.milliseconds) // Ensure that the connection has been released.
            println("Released connection. Pool size: ${db.poolSize()} (idle: ${db.poolIdleSize()})")
        }
    }

    suspend fun exampleTransactions(db: ISQLiteCipher, repo: Sqlx4kRepository) {
        println("\n=== Transactions (SQLCipher) ===")
        // Prepare table
        db.execute("delete from sqlx4k;").getOrThrow()
        db.execute("insert into sqlx4k (id, test) values (1, 'a');").getOrThrow()

        // Manual begin/rollback
        val tx = db.begin().getOrThrow()
        runCatching {
            tx.execute("insert into sqlx4k (id, test) values (2, 'b');").getOrThrow()
            val inside = repo.findAll(tx).getOrThrow()
            println("Inside manual tx before rollback => $inside")
            error("Force rollback")
        }.onFailure {
            tx.rollback().getOrThrow()
        }
        val afterRollback = repo.findAll(db).getOrThrow()
        println("After rollback => $afterRollback")

        // Using transaction helper (auto-commit)
        db.transaction {
            execute("insert into sqlx4k (id, test) values (3, 'c');").getOrThrow()
            // Demonstrate transactional context by passing `this` (Transaction) to repo
            val inside = repo.findAll(this).getOrThrow()
            println("Inside tx helper => $inside")
        }
        val afterCommit = repo.findAll(db).getOrThrow()
        println("After commit => $afterCommit")
    }

    suspend fun exampleTransactionContext(db: ISQLiteCipher) {
        suspend fun doBusinessLogic() {
            val tx = TransactionContext.current()
            tx.execute("update sqlx4k set test = 'tc-updated' where id = 66;").getOrThrow()
            println("doBusinessLogic updated id=66")
        }

        suspend fun doMoreBusinessLogic(): Unit = TransactionContext.withCurrent {
            // Continue in same tx
            fetchAll("select id, test from sqlx4k where id = 66;", Sqlx4kRowMapper).getOrThrow().also {
                println("doMoreBusinessLogic read => $it")
            }
        }

        suspend fun doExtraBusinessLogic(db: ISQLiteCipher): Unit = TransactionContext.withCurrent(db) {
            // If no TransactionContext was present, this would open a new tx; here it reuses the existing one
            fetchAll("select count(*) from sqlx4k;").getOrThrow().also {
                println("doExtraBusinessLogic count rows => $it")
            }
        }

        println("\n=== TransactionContext (coroutines, SQLCipher) ===")
        TransactionContext.new(db) {
            // Seed a record and demonstrate nested helpers participating in same tx
            execute("insert into sqlx4k (id, test) values (66, 'tc');").getOrThrow()
            println("Inserted id=66 in TransactionContext")
            doBusinessLogic()
            doMoreBusinessLogic()
            doExtraBusinessLogic(db)
        }
        println("TransactionContext block completed")
    }
}
